# Generated by Django 4.2.25 on 2025-11-11 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_productvariant_product_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['warehouse_id'], 'verbose_name': 'Остаток на складе', 'verbose_name_plural': 'Остатки на складе'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Движение товара', 'verbose_name_plural': 'Движения товара'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='min_qty',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='qty_on_hand',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='qty_reserved',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='user',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='move_type',
            field=models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход')], max_length=3, verbose_name='Тип движения'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='qty_delta',
            field=models.IntegerField(default=0, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='По умолчанию'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название склада'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Слаг'),
        ),
    ]
