# Generated by Django 4.2.25 on 2025-11-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_options_alter_saleitem_options_and_more'),
        ('inventory', '0002_alter_inventoryitem_options_and_more'),
        ('catalog', '0005_remove_productvariant_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
