# Generated by Django 4.2.25 on 2025-11-11 23:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_productvariant_product_and_more'),
        ('sales', '0002_alter_sale_options_alter_saleitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Позиция чека', 'verbose_name_plural': 'Позиции чека'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=32, unique=True, verbose_name='Номер чека'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], default='cash', max_length=16, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название позиции'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Чек'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sku',
            field=models.CharField(blank=True, max_length=64, verbose_name='SKU / Штрихкод'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product', verbose_name='Товар'),
        ),
    ]
